### ISSUE TITLE
Undefined l:seek?

### ISSUE THREAD

**Issue by NigoroJr** [goldfeld/vim-seek#14]
Hi, I've been using this plugin for some time and I really love how it makes my coding life less stressful. However, I started getting errors whenever I try to seek saying "l:seek not found" after an update about 2 or 3 weeks ago.
Here is the message I get. I don't know a lot about vim script so I'd appreciate some help :)
Thank you!

line    9:
E118: Too many arguments for function: s:seekindex
E15: Invalid expression: s:seekindex(l:line, l:c1, l:c2, l:pos, 'stridx', 's:compareSeekFwd')
line   11:
E121: Undefined variable: l:seek
E15: Invalid expression: l:seek + 1 " to not repeatedly find the same occurence
line   15:
E121: Undefined variable: l:seek
E15: Invalid expression: l:seek == -1 ? -1 : l:pos - 1

**Comment by Gonzih** [comment]
Similar issue here

```
Error detected while processing function <SNR>36_seekBack..<SNR>36_findTargetBwd:                                                                                             
line   10:                                                                                                                                                                    
E118: Too many arguments for function: s:seekindex                                                                                                                            
E15: Invalid expression: s:seekindex(l:haystack, l:c1, l:c2, len(l:haystack), 'strridx', 's:compareSeekBwd')                                                                  
line   12:                                                                                                                                                                    
E121: Undefined variable: l:seek                                                                                                                                              
E15: Invalid expression: l:seek - 1 " to not repeatedly find the same occurence                                                                                               
line   16:                                                                                                                                                                    
E121: Undefined variable: l:seek                                                                                                                                              
E15: Invalid expression: l:seek == -1 ? -1 : l:pos + 1
```

**Comment by goldfeld** [comment]
Thanks for the report guys, major oversight on my part when implementing the new case insensitive seeking, I forgot to change the old case sensitive function to take the new args. 

Since seek now grabs my `set ignorecase` vimrc setting to determine my preference, I forgot to test it for folks not using that. Should be fixed now. By the way, if you do want to try out case insensitive seeks (it's pretty sleek!), you can add `let g:seek_ignorecase = 1` to your vimrc, I haven't got around to updating the README with that.

Please let me know if it's fixed for you.

**Comment by Gonzih** [comment]
Yes, it works now. Thank you!

**Comment by NigoroJr** [comment]
Works perfectly for me, too! Thanks!
Now that it's fixed, I'll close this issue.
