### ISSUE TITLE
Go next by s or ; does not work

### ISSUE THREAD

**Issue by Konfekt** [goldfeld/vim-seek#19]
This is my sneak configuration on Windows 7 64bit Ultimate with gvim 7.4.211:

let g:sneak#s_next = 1
let g:sneak#textobject_z = 0
let g:sneak#use_ic_scs = 1

nmap S <Plug>Sneak_s
nmap R <Plug>Sneak_S
xmap S <Plug>Sneak_s
xmap R <Plug>Sneak_S
omap S <Plug>Sneak_s
omap R <Plug>Sneak_S

After hitting S and entering two letter, neither S or ; will jump to the next match. , does not work neither. If understood correctly, this should work though?

Perhaps it should be mentioned that there are mappings beginning with , and ; in my ,vimrc.

**Comment by goldfeld** [comment]
Hey, vim-seek doesn't have , and ; functionality yet, I assume you mean vim-sneak which is a similar plugin.

**Comment by Konfekt** [comment]
Yep, you are right. Somehow this issue went unnoticed in my inbox.
