### ISSUE TITLE
Don't show seek commands in statusline

### ISSUE THREAD

**Issue by phmarek** [goldfeld/vim-seek#2]
When using the seek motion the statusline shows things like ":call SeekJump()"; either it should keep the last data, or it should say "seeking" (or "cut short before", etc.).

My favourite would be to have it show a hint like ":set showcmd" does, and otherwise keep the statusline as-is (as I frequently have useful data in there).

**Comment by goldfeld** [comment]
Yes, thanks for pointing me towards this. I have made the calls totally silent, in keeping with emulating this as an unobtrusive and as native-feeling motion as possible. Should be working.
