### ISSUE TITLE
Compatibility issues with vim-yankstack

### ISSUE THREAD

**Issue by nickstenning** [goldfeld/vim-seek#6]
This plugin currently doesn't play too nicely with maxbrunsfeld/vim-yankstack, which wraps the behaviour of {c,C,d,D,s,S,x,X,y,Y} in order to capture yanks. Perhaps yankstack needs a way of being told that s/S isn't a yank operation any more? Thoughts, @maxbrunsfeld?

**Comment by goldfeld** [comment]
You could remap seek to another key (customizability is planned within the week), though I really recommend `s` for speed and it seems you don't have a problem with repurposing it. Maybe something about the order in which the plugins' mappings are loaded?

**Comment by goldfeld** [comment]
Oh by the way, seek lets substitute work when it takes a count, so yankstack+seek users could potentially still benefit from capturing multi-char substitutes to yankstack, but then it would probably require more of a concerted solution--@maxbrunsfeld let me know if you guys have any ideas on that.

**Comment by maxbrunsfeld** [comment]
I think @nickstenning's solution in maxbrunsfeld/vim-yankstack/pull/26 is reasonable: just tell yankstack not to touch certain keys. 

Ideally, I'd like a way to wrap a user's existing key bindings with yankstack's logic. This would probably take a little more work though, and could warrant its own vim plugin. I'm imagining a helper command called something like `compose_mapping` that let's you do something like this:

``` vim
  function! some_wrapper_code(existing_mapping)
    " execute some code before
    " then 'call through' to the previous mapping
    normal!  a:existing_mapping
  endfunction

  " then, instead of this:
  map s :call some_wrapper_code<CR>

  " do this:
  compose_mapping s, 'some_wrapper_code'
```

**Comment by goldfeld** [comment]
Yeah, this matter of conflicting plugins and wrapping keybinds is a pain point on some vim-seek features as well. I'll close it as out of scope though for now.
